spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiena-2606/spring-cloud-config-repository.git
          username: qiumingjie126@163.com
          password: jiena_19831126
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9020/eureka/

server:
  port:9019